---
title: "ANPP Data Merging"
author: "Kathy Condon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(tidyverse)
library(dplyr)
library(car)
library(emmeans)
library(multcomp)
library(lmerTest)
library(lme4)
library(RColorBrewer)
library(rstatix)
library(tidyr)
library(ggpubr)
library(lubridate)
library(ggtext)
library(ggh4x)
library(ggpattern)
library(data.table)
library(MuMIn)
library(scales)
library(performance)
library(googledrive)

```

## Set file directories - local
```{r}
dir.create(file.path("deluge"), showWarnings = F)
dir.create(file.path("deluge","data"), showWarnings = F)
dir.create(file.path("deluge","data","R_exports"))
dir.create(file.path("deluge","figures"))
```

# Copy in productivity data from Google Drive
```{r}
#### pull data from Google Drive to local files - one at a time...**select 2 to re-link drive** as needed ####

## list all productivity files in drive by name
prod.files<-c("Linabury_ChANGE_ANPP.csv","CCE_ANPP_2025_R.csv","Condon_SLs_ANPP_byfunctionalgroup.csv","Hajek2024_ANPP.csv","Tooley_DRE_ANPP.csv","Post2020_ANPP.csv","Post2020_BNPP.csv","Post2021_ANPP.csv","Post2021_BNPP.csv","Hoover2022_CPER-DEX_Productivity.csv", "Hoover2022_ANPP_FuncGroup.csv")

## read in drive folder
drive.files<-googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1-z0EMfF8_LTWr3HZVajzcO3K9jKgYM9p"))
  
## read in each file
for (i in prod.files){
  
file.name<-drive.files %>% 
  dplyr::filter(name == i) 

# if-else, to throw error if file name is incorrect or error would otherwise stop loop
if(nrow(file.name) == 1){
  googledrive::drive_download(file = file.name$id, 
                              overwrite = T,
                              path = file.path("deluge", 'data', i))
  
} else{
  message("File error - check name or if duplicated: ", i)
  }
}

```

# Reformat data to all match
- Format to site_id, var, treatment, date, year, doy, value at the plot

```{r Linabury_ChANGE}
lin_CHANGE<-read.csv("deluge/data/Linabury_ChANGE_ANPP.csv")
head(lin_CHANGE)

CHANGE<-lin_CHANGE%>%
  rename(ANPP=anpp,
         trt=treatment,
         GRASS=grass_anpp,
         FORB=forb_anpp)%>%
  mutate(Study_shorthand="Linabury_ChANGE")%>%
  rename(Block=block)%>%
  select(Study_shorthand,Block,plot,trt,year,GRASS,FORB,ANPP)


CHANGE_long<-CHANGE%>%
  pivot_longer(cols=c(GRASS,FORB,ANPP),names_to="funct_group",values_to="ANPP")

head(CHANGE_long)
```

```{r Siggers_CCE}
CCE<-read.csv("deluge/data/CCE_ANPP_2025_R.csv")
head(CCE,5)

siggers_CCE<-CCE%>%
  rename(trt=Treatment,
         year=Year,
         plot=Plot)%>%
  mutate(Study_shorthand="CCE",
         # convert g to g/m2
         C3_grass=C3_g*10,
         C4_grass=C4_g*10,
         Forb=Forb_g*10,
         ANPP=Total_g_m)%>%
  select(Study_shorthand,plot,Block,Replicate,trt,year,C3_grass,C4_grass,Forb,ANPP)%>%
  group_by(Study_shorthand,Block,plot,trt,year)%>%
  dplyr::summarise(
    n.reps=n(),
    C3=mean(C3_grass),
    C4=mean(C4_grass),
    FORB=mean(Forb),
    ANPP=mean(ANPP))

CCE_long<-siggers_CCE%>%
  pivot_longer(cols=C3:ANPP,names_to="funct_group",values_to="ANPP")

head(CCE_long)
```

```{r Condon_SLs}
#### double check this is correct version of data!!! ####
SLs<-read.csv("deluge/data/Condon_SLs_ANPP_byfunctionalgroup.csv")
head(SLs,5)

condon_SLs<-SLs%>%
  rename(trt=new.TRT)%>%
  mutate(Study_shorthand="Condon_SL",
         year=case_when(
           Clip_Type == "clip" ~ "July 2021",
           Clip_Type == "reclip" ~ "July-Sept Regrowth 2021",
           Clip_Type == "clip2" ~ "Sept 2021"
         ),
         ANPP=rowSums(across(C3:WOODY),na.rm=TRUE),
         C3=C3*10,
         C4=C4*10,
         FORB=FORB*10,
         ANNUALS=ANNUALS*10,
         WOODY=WOODY*10,
         ANPP=ANPP*10)%>%
  select(Study_shorthand,Plot,trt,year,C3,C4,FORB,ANNUALS,WOODY,ANPP)

head(condon_SLs,5)

condon_SL_long<-condon_SLs%>%
  pivot_longer(cols=c(C3,C4,FORB,ANNUALS,WOODY,ANPP),names_to="funct_group",values_to="ANPP")

ANPP.avs<-condon_SL_long%>%
  filter(funct_group=="ANPP")%>%
  group_by(year,trt)%>%
  dplyr::summarise(
    n.plots=n(),
    av=mean(ANPP),
    SE=sd(ANPP)/sqrt(n.plots)
  )

head(condon_SL_long,5)

```

```{r "Hajek2024_ANPP.csv"}
Hajek<-read.csv("deluge/data/Hajek2024_ANPP.csv")
head(Hajek,5)

Hajek_24<-Hajek%>%
  rename(trt=Trt,plot=Plot)%>%
  mutate(Study_shorthand="Hajek2024",
         year="2022",
         C3=C3*10,
         C4=C4*10,
         FORB=Forb*10,
         ANNUALS=Annual*10,
         ANPP=Total_biomass*10)%>%
  select(Study_shorthand,plot,Rep,trt,year,C3,C4,FORB,ANNUALS,ANPP)

head(Hajek_24,5)

Hajek_24_long<-Hajek_24%>%
  pivot_longer(cols=c(C3,C4,FORB,ANNUALS,ANPP),names_to="funct_group",values_to="ANPP")%>%
  group_by(Study_shorthand,year,plot,trt,funct_group)%>%
  dplyr::summarise(
    n.its=n(),
    plot.av=mean(ANPP,na.rm=TRUE),
    plot.sd=sd(ANPP,na.rm=TRUE))%>%
  rename(ANPP=plot.av)

head(Hajek_24_long,5)

```

```{r "Tooley_DRE_ANPP.csv"}
Tooley<-read.csv("deluge/data/Tooley_DRE_ANPP.csv")
head(Tooley,5)

Tooley_DRE<-Tooley%>%
rename(year=Year,trt=WaterTreatment,legacy=Treatment,Block=Shelter,plot=Plot)%>%
mutate(trt2=paste("Leg.",legacy,"_Trt.",trt,sep=""))%>%
mutate(Study_shorthand="Tooley_DRE",
       C3=GrassC3*10,
       C4=GrassC4Per*10,
       FORB=Forb*10,
       C4.ANNUALS=GrassC4An*10, # only C4 annuals -- which ones?? And no C3??
       ANPP=ANPP*10)%>%
select(Study_shorthand,plot,Iteration,Block,trt,trt2,year,C3,C4,FORB,C4.ANNUALS,ANPP)

Tooley_DRE_long<-Tooley_DRE%>%
  select(Study_shorthand,plot,Iteration,Block,trt2,year,C3,C4,FORB,C4.ANNUALS,ANPP)%>%
  rename(trt=trt2)%>%
  pivot_longer(cols=c(C3,C4,FORB,C4.ANNUALS,ANPP),names_to="funct_group",values_to="ANPP")%>%
  group_by(Study_shorthand,Block,plot,trt,year,funct_group)%>%
  dplyr::summarise(
    n.reps=n(),
    ANPP=mean(ANPP))

head(Tooley_DRE_long,5)

```

```{r "Post2020_ANPP.csv" & "Post2020_BNPP.csv"}
### ANPP ###
Post20<-read.csv("deluge/data/Post2020_ANPP.csv")
head(Post20,5)

Post2020<-Post20%>%
  rename(trt=Trt,plot=Plot)%>%
  mutate(Study_shorthand="Post2020",
         year="2017",
         GRASS=Grass_total*10,
         FORB=Forb_mass*10,
         ANPP=Total_biomass*10)%>%
  select(Study_shorthand,plot,Rep,trt,year,GRASS,FORB,ANPP)

head(Post2020)

Post2020_long<-Post2020%>%
  pivot_longer(cols=c(GRASS,FORB,ANPP),names_to="funct_group",values_to="ANPP")%>%
  group_by(Study_shorthand,year,plot,trt,funct_group)%>%
  dplyr::summarise(
    n.its=n(),
    plot.av=mean(ANPP),
    plot.sd=sd(ANPP))%>%
  rename(ANPP=plot.av)
  
### BNPP ###
Post20<-read.csv("deluge/data/Post2020_BNPP.csv")
head(Post20,5)

Post2020_BNPP<-Post20%>%
  rename(trt=Trt,plot=Plot,depth=Depth)%>%
  mutate(Study_shorthand="Post2020",
         year="2017")%>%
  select(Study_shorthand,year,plot,trt,depth,BNPP)%>%
  group_by(Study_shorthand,year,trt,plot)%>% # sum depths together (t = top, b = bottom)
  dplyr::summarise(
    n.depths=n(),
    BNPP.gm2=sum(BNPP),
    .groups="drop"
  )

head(Post2020_BNPP)

### merge 
head(Post2020_long)
head(Post2020_BNPP)

Post2020_merged<-Post2020_long%>%
  left_join(Post2020_BNPP %>% select(-n.depths),
            by=c("Study_shorthand","year","plot","trt"))%>%
  select(Study_shorthand,year,plot,trt,funct_group,ANPP,BNPP.gm2)%>%
  rename(BNPP=BNPP.gm2)%>%
  mutate(BNPP=ifelse(funct_group=="ANPP",BNPP,"NA"))

head(Post2020_merged,5)
sum(is.na(Post2020_merged$BNPP)) # 3 plots missing - 29, 31, 32

```

```{r "Post2021_ANPP.csv","Post2021_BNPP.csv"}
### ANPP ###
Post21<-read.csv("deluge/data/Post2021_ANPP.csv")
head(Post21,5)

Post2021<-Post21%>%
  rename(trt=Trt,plot=Plot)%>%
  mutate(Study_shorthand="Post2021",
         year="2018",
         GRASS=Grass_total*10,
         FORB=Forb_mass*10,
         ANPP=Total_biomass*10)%>%
  select(Study_shorthand,plot,Rep,trt,year,GRASS,FORB,ANPP)

head(Post2021)

Post2021_long<-Post2021%>%
  pivot_longer(cols=c(GRASS,FORB,ANPP),names_to="funct_group",values_to="ANPP")%>%
  group_by(Study_shorthand,year,plot,trt,funct_group)%>%
  dplyr::summarise(
    n.its=n(),
    plot.av=mean(ANPP),
    plot.sd=sd(ANPP),
    .groups="drop")%>%
  rename(ANPP=plot.av)
  
### BNPP ###
Post21<-read.csv("deluge/data/Post2021_BNPP.csv")
head(Post21,5)

Post2021_BNPP<-Post21%>%
  rename(trt=Trt,plot=Plot,depth=Depth)%>%
  mutate(Study_shorthand="Post2021",
         year="2018")%>%
  select(Study_shorthand,year,plot,trt,depth,BNPP)%>%
  group_by(Study_shorthand,year,trt,plot)%>% # sum depths together (T/M/B - top, middle, bottom)
  dplyr::summarise(
    n.depths=n(),
    BNPP.gm2=sum(BNPP),
    .groups="drop"
  )

head(Post2021_BNPP)

### merge 
head(Post2021_long)
head(Post2021_BNPP)

Post2021_merged<-Post2021_long%>%
  left_join(Post2021_BNPP %>% select(-n.depths),
            by=c("Study_shorthand","year","plot","trt"))%>%
  select(Study_shorthand,year,plot,trt,funct_group,ANPP,BNPP.gm2)%>%
  rename(BNPP=BNPP.gm2)%>%
  mutate(BNPP=ifelse(funct_group=="ANPP",BNPP,"NA"))

head(Post2021_merged,5)
sum(is.na(Post2021_merged$BNPP)) # 0 plots missing

```

```{r "Hoover2022_CPER-DEX_Productivity.csv"}
Hoover2022_CPER_DEX<-read.csv("deluge/data/Hoover2022_CPER-DEX_Productivity.csv")
head(Hoover2022_CPER_DEX,5)

Hoover2022<-Hoover2022_CPER_DEX%>%
  rename(trt=treatment,ANPP=anpp,BNPP=bnpp)%>%
  mutate(Study_shorthand="Hoover2022_CPER_DEX",
         year="2019")%>%
  select(Study_shorthand,plot,trt,year,ANPP,BNPP)

head(Hoover2022,5)

```


```{r "Hoover2022_ANPP_FuncGroup.csv"}
# the functional group for Hoover vs. just overall
Hoover2022_CPER_DEX.fg<-read.csv("deluge/data/Hoover2022_ANPP_FuncGroup.csv")
head(Hoover2022_CPER_DEX.fg,5)

Hoover2022.fg<-Hoover2022_CPER_DEX.fg%>%
  select(-c(Site, Trtnum, Date.Collected, Date.Weighed, Soil_Moisture, Notes, BOGR.Flower.Stem.Ct, Cactus.percent)) %>%
  rename(trt=Treatment,plot=Plot)%>%
   pivot_longer(cols=c(C3, C4, Forb, Annual, Woody),names_to="funct_group",values_to="ANPP")%>%
  mutate(Study_shorthand="Hoover2022_CPER_DEX",
         year="2019", 
         ANPP = ANPP *10) %>%
  group_by(Study_shorthand,year,plot,trt,funct_group)%>%
  dplyr::summarise(
    plot.av=mean(ANPP),
    .groups="drop")%>%
  rename(ANPP=plot.av) %>%
  mutate(trt = case_when(
    trt == "ambient (no roof)" ~ "AMB", 
    trt == "control" ~ "CON",
    trt == "drought" ~ "DRT",
    trt == "drought + deluge" ~ "DRT+DEL",
    trt == "drought + small" ~ "DRT+SE",
    TRUE ~ trt
  ))


```


```{r Check all}
CHANGE_long
CCE_long
condon_SL_long
Hajek_24_long
Tooley_DRE_long
Post2020_merged
Post2021_merged
Hoover2022
Hoover2022.fg

# final consistencies
# Standardize each dataframe to have the same columns
CHANGE_clean<-CHANGE_long%>%
  select(Study_shorthand, year, Block, plot, trt, funct_group, ANPP)%>%
  mutate(BNPP = NA, year = as.character(year))

CCE_clean<-CCE_long%>%
  select(Study_shorthand, year, Block, plot, trt, funct_group, ANPP)%>%
  mutate(BNPP = NA, year = as.character(year), 
         plot = as.integer(plot), trt = as.character(trt))

condon_SL_clean<-condon_SL_long%>%
  rename(plot = Plot)%>%
  mutate(Block = NA)%>%
  select(Study_shorthand, year, Block, plot, trt, funct_group, ANPP)%>%
  mutate(BNPP = NA)

Hajek_24_clean<-Hajek_24_long%>%
  mutate(Block = NA)%>%
  select(Study_shorthand, year, Block, plot, trt, funct_group, ANPP)%>%
  mutate(BNPP = NA)

Tooley_DRE_clean<-Tooley_DRE_long%>%
  select(Study_shorthand, year, Block, plot, trt, funct_group, ANPP)%>%
  mutate(BNPP = NA, year = as.character(year))
## double-check Greg's averages
Tooley_DRE_extracheck<-Tooley_DRE_clean%>%
  group_by(year,funct_group,trt)%>%
  dplyr::summarise(
    n.plots=n(),
    ANPP.avs=mean(ANPP)
  )

Post2020_clean<-Post2020_merged%>%
  mutate(Block = "NA")%>%
  select(Study_shorthand, year, Block, plot, trt, funct_group, ANPP, BNPP)

Post2021_clean<-Post2021_merged%>%
  mutate(Block = "NA")%>%
  select(Study_shorthand, year, Block, plot, trt, funct_group, ANPP, BNPP)

Hoover2022_clean<-Hoover2022%>%
  mutate(Block = "NA")%>%
  mutate(funct_group = "ANPP", year = as.character(year))%>%
  select(Study_shorthand, year, Block, plot, trt, funct_group, ANPP, BNPP)

Hoover2022fg_clean <- Hoover2022.fg %>%
  select(Study_shorthand, year,plot, trt, funct_group, ANPP) %>%
  mutate(Block = "NA", BNPP = NA, year = as.character(year))

# Stack them all
ANPP_BNPP_harmonized<-rbind(CHANGE_clean, CCE_clean, condon_SL_clean,
                      Hajek_24_clean, Tooley_DRE_clean,
                      Post2020_clean, Post2021_clean, Hoover2022_clean, Hoover2022fg_clean)

head(ANPP_BNPP_harmonized,5)
```

```{r export to drive}
# Export and write to the drives
# Save your data frame locally first
write.csv(x = ANPP_BNPP_harmonized, row.names = F, na = '',
          file = file.path("deluge", "data", "R_exports","ANPP_harmonized.csv"))

# Upload to Drive
drive_upload(
  media = "ANPP_harmonized.csv",
  path = file.path("deluge", "data","R_exports"),
  name = "ANPP_harmonized.csv",
  overwrite = T)

```




