---
title: "anpp_extraction_KVC"
author: "Kathy Condon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(googledrive)
library(broom)
library(corrplot)

theme_set(theme_bw(12))

```

## Set file directories - local
```{r}
dir.create(file.path("deluge"), showWarnings = F)
dir.create(file.path("deluge","data"), showWarnings = F)
dir.create(file.path("deluge","data","R_exports"))
```

# Read in ANPP, precip, and trt info
```{r Siggers CCE pull}
#### pull data from Google Drive to local files - one at a time ####
# fi.name<-"CCE_ANPP_2025_R.csv"
# fi.name<-"CCE_VWC_Year2.csv"
# fi.name<-"CCE_GCC_updated.csv"

googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1-z0EMfF8_LTWr3HZVajzcO3K9jKgYM9p")) %>% 
  dplyr::filter(name == fi.name) %>% 
  googledrive::drive_download(file = .$id, overwrite = T,
                              path = file.path("deluge", 'data', .$name))
```

```{r Siggers CEE data}
#### Read data from local files ####
CCE_anpp<-read.csv("deluge/data/CCE_ANPP_2025_R.csv")%>%
  rename(perc_Cactus=Cactus_.,
         stalks=Bouteloua_gracilis_stalks)%>%
  mutate(C3_grass=(C3_g*10),
         C4=(C4_g*10),
         FORB=(Forb_g*10),
         TOTAL=Total_g_m)%>%
  select(Year,Block,Plot,Treatment,Replicate,C3_grass,C4,FORB,TOTAL,perc_Cactus,stalks)
  
str(CCE_anpp)

CCE_VWC<-read.csv("deluge/data/CCE_VWC_Year2.csv")%>%
  rename(Plot=Plot_.,
         TRT=Trt_.,
         VWC=X20_cm_VWC_.,
         Notes=X)%>%
  mutate(new.Date=as.Date(Date,format="%m/%d/%y"))%>%
  select(Plot,TRT,new.Date,VWC,Notes)

str(CCE_VWC)

CCE_GCC<-read.csv("deluge/data/CCE_GCC_updated.csv")%>%
  rename(Plot=plot,
         Block=block,
         TRT=treatment,
         GCC=GCC_mean)%>%
  mutate(new.Date=as.Date(Date,format="%m/%d/%y"))%>%
  filter(!DoY=="232")%>%
  select(Plot,Block,TRT,new.Date,GCC,file_name)
  
str(CCE_GCC)

#### pull treatments and rename ####
CCE_trts<-CCE_VWC%>%
  filter(new.Date=="2025-05-23")%>%
  select(Plot,TRT)%>%
  mutate(TRT_name=case_when(
    TRT == "Drought" ~ "Dr",
    TRT == "Drought-Deluge" ~ "Dr_Del",
    TRT == "Control" ~ "A",
    TRT == "Deluge" ~ "Del"))%>%
  select(Plot,TRT_name)


#### add treatments names to all datasets ####
Siggers_ANPP<-merge(CCE_anpp,CCE_trts,by="Plot")
str(Siggers_ANPP)

Siggers_VWC<-merge(CCE_VWC,CCE_trts,by="Plot")
str(Siggers_VWC)

Siggers_GCC<-merge(CCE_GCC,CCE_trts,by="Plot")
str(Siggers_GCC)

#### Seasonal averages ####
Siggers_ANPP_plots_avs<-Siggers_ANPP%>%
  pivot_longer(cols=C3_grass:TOTAL,names_to="funct_group",values_to="gm2")%>%
  group_by(Year,Plot,Block,TRT_name,funct_group)%>%
  dplyr::summarise(
    n.its=n(),
    plot.anpp=mean(gm2))

Siggers_ANPP_avs<-Siggers_ANPP_plots_avs%>%
  group_by(Year,TRT_name,funct_group)%>%
  dplyr::summarise(
    n.plots=n(),
    ANPP.av=mean(plot.anpp),
    ANPP.sd=sd(plot.anpp),
    ANPP.SE=ANPP.sd/sqrt(n.plots))

filter(Siggers_ANPP_avs,funct_group=="TOTAL")

```

```{r Condon Ecosphere}
#### pull data from local file ####
Con_21<-read.csv("/Users/Kathy/Desktop/SGS Research/SGS Legacies/Ecosphere MS Submission/Analysis/Spring Legacies Ecosphere Submission/SGS_SLs_ANPP_all.csv")
str(Con_21)

#### Seasonal averages ####
Con_21_ANPP_avs<-Con_21%>%
  group_by(Clip_Type,TRT)%>%
  dplyr::summarise(
    n.plots=n(),
    ANPP.av=mean(ANPP),
    ANPP.sd=sd(ANPP),
    ANPP.SE=ANPP.sd/sqrt(n.plots))

# view(Con_21_ANPP_avs)

```

```{r Tooley DRE}
fi.name<-"Tooley_DRE_ANPP.csv"

googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1-z0EMfF8_LTWr3HZVajzcO3K9jKgYM9p")) %>% 
  dplyr::filter(name == fi.name) %>% 
  googledrive::drive_download(file = .$id, overwrite = T,
                              path = file.path("deluge", 'data', .$name))

Tooley_DRE<-read.csv("deluge/data/Tooley_DRE_ANPP.csv")
str(Tooley_DRE)

#### Seasonal averages ####
Tooley_ANPP<-Tooley_DRE%>%
  pivot_longer(cols=c(GrassC3:ANPP),names_to="funct_group",values_to="not_scaled")%>%
  mutate(gm2=not_scaled*10)%>%
  group_by(Year,Treatment,WaterTreatment,Plot,funct_group)%>%
  dplyr::summarise(
    n.its=n(),
    plot.anpp=mean(gm2))

Tooley_ANPP_avs<-Tooley_ANPP%>%
  group_by(Year,Treatment,WaterTreatment,funct_group)%>%
  dplyr::summarise(
    n.plots=n(),
    ANPP.av=mean(plot.anpp),
    ANPP.sd=sd(plot.anpp),
    ANPP.SE=ANPP.sd/sqrt(n.plots))%>%
  filter(funct_group=="ANPP")

```

```{r All Papers ANPP from TRT Table file}
fi.name<-"treatment_table_copy.csv"

googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1-z0EMfF8_LTWr3HZVajzcO3K9jKgYM9p")) %>% 
  dplyr::filter(name == fi.name) %>% 
  googledrive::drive_download(file = .$id, overwrite = T,
                              path = file.path("deluge", 'data', .$name))

all_trts<-read.csv("deluge/data/treatment_table_copy.csv")%>%
  select(Study,Treatment,Summary,study_year,n,Deluge_Control,Deluge,Deluge_size_mm,Deluge_month,mean_ANPP,se_ANPP)


str(all_trts)
view(all_trts)

### clean table ###
fi.name<-"DelSize_ANPPResp.csv"

googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1-z0EMfF8_LTWr3HZVajzcO3K9jKgYM9p")) %>% 
  dplyr::filter(name == fi.name) %>% 
  googledrive::drive_download(file = .$id, overwrite = T,
                              path = file.path("deluge", 'data', .$name))

all_trts<-read.csv("deluge/data/DelSize_ANPPResp.csv")%>%
  mutate(other_group=factor(other_group))%>%
  mutate(amb_con=factor(amb_con))

str(all_trts)
```

```{r ANPP response with deluge size graph}
str(all_trts)

# add theme 
library(knitr)
library(tidyverse)
library(dplyr)
library(car)
library(emmeans)
library(multcomp)
library(lmerTest)
library(lme4)
library(RColorBrewer)
library(rstatix)
library(tidyr)
library(ggpubr)
library(lubridate)
library(ggtext)
library(ggh4x)
library(ggpattern)
library(data.table)
library(MuMIn)
library(scales)
library(performance)

plot_theme<-theme_classic()+
  theme(
    strip.background=element_blank(),
    strip.text.x=element_text(size=12,
                              hjust=0,
                              face="bold",colour="black"),
    strip.text.y=element_text(size=12,
                              hjust=0,
                              face="bold",colour="black"),
    panel.background=element_rect(fill="transparent"),
    panel.border=element_rect(fill="transparent",color="black",
                              linewidth=0.5),
    plot.background=element_rect(fill="transparent",color=NA),
    legend.background=element_rect(fill="transparent"),
    legend.position="right",
    # legend.title=element_text(size=16,face="bold"),
    legend.text=element_text(size=12),
    # axis.line.x=element_line(linewidth=1,color="black"),
    axis.line.x=element_blank(),
    axis.line.y=element_blank(),
    axis.ticks=element_line(linewidth=0.5,color="black"),
    axis.ticks.length=unit(-0.05,"in"),
    axis.title = element_text(size=12,
                              colour="black",face="bold"),
    axis.text=element_text(size=10,colour="black"),
    axis.text.x=element_text(angle=0,hjust=0.5,colour="black"),
    axis.text.y=element_text(colour="black"),
    plot.title=element_text(size=12),
    strip.placement="outside")


perc.diff<-ggplot(all_trts,aes(x=deluge_mm,y=perc_diff,color=other_group,shape=amb_con,label=Study))+
  geom_point(size=3)+
  # geom_line(aes(linetype=other_group))+
  geom_text(hjust=1,vjust=-0.6)+
  labs(x="Deluge size (mm)",y="ANPP percent difference")+
  theme_classic()+
  plot_theme

perc.diff



```
