---
title: "Continuous_Exploration_GCC-VWC-SR"
author: "Kathy Condon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(tidyverse)
library(dplyr)
library(car)
library(emmeans)
library(multcomp)
library(lmerTest)
library(lme4)
library(RColorBrewer)
library(rstatix)
library(tidyr)
library(ggpubr)
library(lubridate)
library(ggtext)
library(ggh4x)
library(ggpattern)
library(data.table)
library(MuMIn)
library(scales)
library(performance)
library(googledrive)
```

```{r set file directories - local}
dir.create(file.path("deluge"), showWarnings = F)
dir.create(file.path("deluge","data"), showWarnings = F)
dir.create(file.path("deluge","data","R_exports"))
dir.create(file.path("deluge","figures"))
```

```{r read in continuous files - choose 2 to refresh connection}
drive.files<-googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1dmzGwkGC1Y4uWW8nLXDkhtB_4A4suyF3?usp=drive_link"))

cont.files<-c("GCC_filtered.csv","SR_filtered.csv","VWC_20cm_filtered.csv","deluge_characteristics_mergeable.csv")

## read in each file
for (i in cont.files){
  
file.name<-drive.files %>% 
  dplyr::filter(name == i) 

# if-else, to throw error if file name is incorrect or error would otherwise stop loop
if(nrow(file.name) == 1){
  googledrive::drive_download(file = file.name$id, 
                              overwrite = T,
                              path = file.path("deluge", 'data', i))
  
} else{
  message("File error - check name or if duplicated: ", i)
  }
}

```

```{r check files}
GCC<-read.csv("deluge/data/GCC_filtered.csv")
str(GCC)

VWC<-read.csv("deluge/data/VWC_20cm_filtered.csv")
str(VWC)

SR<-read.csv("deluge/data/SR_filtered.csv")
str(SR)

#### set up deluge characteristics data to merge with
del.info<-read.csv("deluge/data/deluge_characteristics_mergeable.csv")
# view(del.info)
```

```{r fix rest of data for merge}
GCC.dat<-GCC%>%
  mutate(var=as.numeric(GCC))

VWC.dat<-VWC%>%
  mutate(var=as.numeric(VWC))

SR.dat<-SR%>%
  mutate(var=as.numeric(efflux))

con.dat<-list(VWC.dat,GCC.dat,SR.dat)
con.labels<-list("20 cm VWC (%)","GCC","Efflux")
```

```{r loop continuous data manipulations}
# Make a for loop to clean and average data
### set empty list for output of changed data
con.raw.adj<-list()
con.av.adj<-list()

con.merge<-list()
con.merge.check<-list()


### check lists
lapply(con.dat,head,5)
con.labels

### cleanup and average data
for (i in seq_along(con.dat)){
  dat<-con.dat[[i]] # get first dataframe from list
  y.lab<-con.labels[[i]] # get matching y-axis label from list of labels
  
  # make data adjustments
  cleanup.dat<-dat%>%
    mutate(new.date=as.Date(date,format="%Y-%m-%d"),
         trt=factor(trt),
         Study_shorthand=factor(Study_shorthand))%>%
    mutate(year=year(new.date),
         mon=month(new.date))
  # save 
  con.raw.adj[[i]]<-cleanup.dat
  
  # get DAILY AVERAGES (collapse plots down to one value per trt per day)
  daily.avs<-cleanup.dat%>%
    group_by(Study_shorthand,new.date,year,trt)%>%
    filter(!is.na(var))%>%
    dplyr::summarise(
      plots.per.trt=n(),
      av=mean(var),
      sd=sd(var),
      SE=sd/sqrt(plots.per.trt))%>%
  mutate(trt_type=if_else(grepl("DEL",trt),"DEL","CON"))%>%
  mutate(Study_trt=paste(Study_shorthand,trt,sep=": "))
  
  # add in deluge characteristics info
  merge.daily<-merge(daily.avs,del.info,by=c("Study_shorthand","year","trt"))
  head(merge.daily,5)
  
  # cleanup dates again and split out Alex and Greg (paired controls DR with DR+DEL and CON with CON+DEL)
  daily<-merge.daily%>%
  mutate(doy.date=yday(new.date),
         del_start=as.Date(del_start,format="%m/%d/%y"),
         del_end=as.Date(del_end,format="%m/%d/%y"))%>%
  mutate(background=case_when(
    Study_shorthand %in% c("CCE","Tooley_DRE") & trt_type=="DEL" ~ str_remove(as.character(trt),"_DEL$"),
    Study_shorthand %in% c("CCE","Tooley_DRE") & trt_type=="CON"~as.character(trt)))%>%
    mutate(label=y.lab)
  
  # save
  con.av.adj[[i]]<-daily
  
  # make columns side-by-side control (duplicated when needed) & deluge treatments
  ### split into control and deluge data frames
  con_daily<-daily%>%
    filter(trt_type=="CON")%>%
    select(Study_shorthand,year,new.date,CON_type=Study_trt,CON_n=plots.per.trt,CON_av=av,CON_sd=sd,CON_SE=SE,doy.date,background)
  
  del_daily<-daily%>%
    filter(trt_type=="DEL")%>%
    select(Study_shorthand,year,new.date,DEL_type=Study_trt,DEL_n=plots.per.trt,DEL_av=av,DEL_sd=sd,DEL_SE=SE,del_start,del_end,doy.date,background)
  
  # merge to make a WIDE DF (don't use pivot_wider b/c going to be hard to duplicate right and check NA's, etc.)
  full.merge.wide<-merge(con_daily,del_daily,by=c("Study_shorthand","year","new.date","doy.date","background"),all=TRUE)
  print(head(full.merge.wide,5))
  
  ### check missing dates that were not matched
  full.merge.check<-full.merge.wide%>%
    filter(is.na(CON_av) | is.na(DEL_av))
  print(full.merge.check)
  # save check
  con.merge.check[[i]]<-full.merge.check
  
  # CALCULATE WITHIN 20%
  full.merge.wide<-full.merge.wide%>%
    mutate(perc_diff=((DEL_av-CON_av)/CON_av)*100)%>%
    mutate(del_response=case_when(
      perc_diff < -20 ~ "NEGATIVE",
      perc_diff >= 20 ~ "POSITIVE",
      TRUE ~ "none"))%>%
    mutate(label=y.lab)%>%
    select(Study_shorthand,year,new.date,del_start,del_end,doy.date,CON_type,DEL_type,CON_n,DEL_n,CON_av,DEL_av,perc_diff,del_response,label)
  
  # save merged data
  con.merge[[i]]<-full.merge.wide
  
}

# check dataframe first few lines look correct (use label column to see what var)
lapply(con.merge,head,5)

# view(con.merge[[2]])

lapply(con.av.adj,head,5)

# check any missing dates that did not match in the CON + DEL merge
con.merge.check

# view(con.merge[[1]])

# bind all rows and export
# bind rows
response.periods<-bind_rows(con.merge)

# Export locally
write.csv(x = response.periods, file = file.path("deluge", "data", "R_exports", "VWC_GCC_SR_wide-response-periods_bydate.csv"))

# Upload to Drive
googledrive::drive_upload(media = file.path("deluge", "data", "R_exports", "VWC_GCC_SR_wide-response-periods_bydate.csv"), overwrite = T,
                        path = googledrive::as_id("https://drive.google.com/drive/folders/1dmzGwkGC1Y4uWW8nLXDkhtB_4A4suyF3"))

# bind rows
daily.avs<-bind_rows(con.av.adj)

# Export locally
write.csv(x = daily.avs, file = file.path("deluge", "data", "R_exports", "VWC_GCC_SR_long-dailyavs.csv"))

# Upload to Drive
googledrive::drive_upload(media = file.path("deluge", "data", "R_exports", "VWC_GCC_SR_long-dailyavs.csv"), overwrite = T,
                        path = googledrive::as_id("https://drive.google.com/drive/folders/1dmzGwkGC1Y4uWW8nLXDkhtB_4A4suyF3"))

######## NEXT STEPS ########
# continuing with full.merge.wide from above, think about good way to organize table or use "del_response" column to highlight on graph when consecutive days remaining different ends--define as deluge response period length for each

#### Using relative 20% from ranges instead ####
### get ranges for each measurement (label) across all years and studies -- TOTAL ranges -- **THIS WILL NEED TO BE ADJUSTED to drop Mary first year if we don't want that or any others! **
rel.20.across<-response.periods%>%
  group_by(label)%>%
  # filter(!Study_shorthand=="ChANGE" & year==)%>%
  summarise(range_across_studyyrs=max(CON_av,na.rm=TRUE)-min(CON_av,na.rm=TRUE)) 

### get ranges for each within each study and year -- this may be more relevant if we want to consider asymmetric responses -- so dry years are weighted differently than wet
rel.20.within<-response.periods%>%
  group_by(label,Study_shorthand,year)%>%
  summarise(range_within_studyyrs=max(CON_av,na.rm=TRUE)-min(CON_av,na.rm=TRUE))

#### metric comparisons ####
# compare 20% of control (raw) vs. 20% relative to total range vs. 20% relative to range in that study/year
all.comps<-response.periods%>%
  left_join(rel.20.across,by="label")%>%
  left_join(rel.20.within,by=c("label","Study_shorthand","year"))%>%
  mutate(range_diff_across=((DEL_av-CON_av)/range_across_studyyrs)*100,
         del_response_across=case_when(
           range_diff_across <= -20 ~ "NEGATIVE",
           range_diff_across >= 20 ~ "POSITIVE",
           TRUE ~ "none"),
         range_diff_within=((DEL_av-CON_av)/range_within_studyyrs)*100,
         del_response_within=case_when(
           range_diff_within <= -20 ~ "NEGATIVE",
           range_diff_within >= 20 ~ "POSITIVE",
           TRUE ~ "none"))

# comparison of how many dates flagged under each method
all.comps %>%
  group_by(label) %>%
  summarise(
    original = sum(del_response != "none", na.rm=TRUE),
    across_range = sum(del_response_across != "none", na.rm=TRUE),
    within_range = sum(del_response_within != "none", na.rm=TRUE)) 

```

```{r graphing deluges}
study.names<-bind_rows(con.av.adj)%>%
  distinct(Study_shorthand)%>%
  pull(Study_shorthand)


for (i in con.av.adj){
  for (s in study.names){
    
    dat<-i%>%
      filter(Study_shorthand==s)
    
    if (nrow(dat)==0) next
    
    y.lab<-unique(dat$label)
    
    # get positive response dates
    pos.dates.con<-all.comps%>%
      filter(Study_shorthand==s,
             label==y.lab,
             del_response_across=="POSITIVE",
             grepl("CON$",CON_type))
    
    pos.dates.dr<-all.comps%>%
      filter(Study_shorthand==s,
             label==y.lab,
             del_response_across=="POSITIVE",
             grepl("DR$",CON_type))
    
    # get negative response dates
    neg.dates.con<-all.comps%>%
      filter(Study_shorthand==s,
             label==y.lab,
             del_response_across=="NEGATIVE",
             grepl("CON$",CON_type))
    
    neg.dates.dr<-all.comps%>%
      filter(Study_shorthand==s,
             label==y.lab,
             del_response_across=="NEGATIVE",
             grepl("DR$",CON_type))
    
    # plot lines for trts and wrap w/ years
    plot<-ggplot(dat,aes(x=doy.date,y=av,group=trt,linetype=trt_type,color=Study_trt)) +
      geom_rect(aes(xmin=yday(del_start),xmax=yday(del_end),ymin=-Inf,ymax=Inf),color="lightblue",fill="lightblue",linetype="solid")+
      geom_line() +
      geom_point() +
      geom_errorbar(aes(ymin=av-SE, ymax=av+SE), width=0.2) +
      geom_text(data=pos.dates.con,aes(x=doy.date,y=max(dat$av,na.rm=TRUE)*1.05),
                label="+",color="green4",size=3,inherit.aes=FALSE)+
      geom_text(data=neg.dates.con,aes(x=doy.date,y=max(dat$av,na.rm=TRUE)*1.05),
                label="-",color="red4",size=3,inherit.aes=FALSE)+
      geom_text(data=pos.dates.dr,aes(x=doy.date,y=min(dat$av,na.rm=TRUE)*0.95),
                label="+",color="green4",size=3,inherit.aes=FALSE)+
      geom_text(data=neg.dates.dr,aes(x=doy.date,y=min(dat$av,na.rm=TRUE)*0.95),
                label="-",color="red4",size=3,inherit.aes=FALSE)+
      # scale_x_date(date_labels="%b %d") +
      facet_wrap(~year)+
      labs(
        x="Date",
        y=y.lab,
        title=s,
        linetype="Treatment")+
      theme_bw()+
      theme(legend.position="right")+
      force_panelsizes(rows = unit(2.25, "in"),
                   cols = unit(4.25, "in"))
    
    filename<-paste0("/Users/Kathy/Desktop/",s,"_",y.lab,".png")
    ggsave(filename,plot,width=12,height=5)
  }
  
}

view(all.comps)
```

```{r monthly}



```




