---
title: "Greenness Extraction"
author: "OLH"
date: "2026-03"
output: 
  bookdown::html_document2:
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: TRUE
    collapsed: TRUE
    theme: spacelab
    fig_caption: TRUE
    number_sections: FALSE
---
# Setup
<style>h1 {font-size: 24pt; } h2 {font-size: 20pt; } h3 {font-size: 18pt; } h4 {font-size: 16pt; } h5 {font-size: 14pt; } h6 {font-size: 12pt; } </style> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, dpi = 600, progress = FALSE, cache = FALSE, fig.width=5,  fig.height=3.5, fig.align="center")

options(repos = c(CRAN = "http://cran.rstudio.com"))
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, googledrive, supportR, lubridate)

`%!in%` = Negate(`%in%`)

```

# Create Folders on Desktop
```{r}
dir.create(file.path("deluge"), showWarnings = F)
dir.create(file.path("deluge", 'data'), showWarnings = F)
dir.create(file.path("deluge", 'data', 'R_exports'), showWarnings = F)
```

# Download VWC files
```{r}
# Identify wanted files
files_drive <- googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1-z0EMfF8_LTWr3HZVajzcO3K9jKgYM9p")) %>% 
  dplyr::filter(stringr::str_detect(string = .$name, pattern = "GCC.*\\.csv|\\.csv.*GCC"))

# Did that work?
files_drive

# Identify local files
files_local <- dir(path = file.path("deluge", "data"))
files_local

# Overwrite local data files?
update <- TRUE

# Identify desired files
if(update == T) {
  files_wanted <- files_drive 
} else {
  files_wanted <- files_drive %>%
    dplyr::filter(!name %in% files_local)
}

# Download them!
purrr::walk2(.x = files_wanted$id, .y = files_wanted$name,
             .f = ~ googledrive::drive_download(file = .x, overwrite = T,
                                                path = file.path("deluge", "data", .y)))


```

# Read in all of the data
```{r}

# Get list of files with VWC in the filename
gcc_files <- list.files(path = file.path("deluge", "data"), 
                        pattern = "GCC", 
                        full.names = TRUE)

# Read each file and assign to a dataframe named after the file
for(f in gcc_files) {
  # Extract just the filename without extension as the object name
  obj_name <- tools::file_path_sans_ext(basename(f))
  
  # Read the CSV and assign to an object with that name
  assign(obj_name, read.csv(f))
}

```

# Process Individual Files

## Hajek 2024

```{r}
str(Hajek2024_GCC)
hajek2024 <- Hajek2024_GCC %>%
  rename(plot = "Plot", 
         trt = "Trt", 
         date = "Date", 
         GCC = "Greenness") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Hajek2024", 
         # add in the variable analyzed
         Variable = "GCC", 
         date = as.Date(date, format = "%d-%b-%y"), 
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA)
  
str(hajek2024)

# check na's
hajek2024%>%
  filter(is.na(GCC)) # none

# check avs
hajek.avs<-hajek2024%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=n(),
    GCC.av=mean(GCC),
    GCC.sd=sd(GCC))

# view(hajek.avs) # all looks fine, leave alone
```
## Hoover et al. 2022

```{r}
str(`Hoover2022_CPER-DEX_GCC`)

hoover2022 <- `Hoover2022_CPER-DEX_GCC` %>%
  rename( 
         trt = "treatment", 
         GCC = "greenness") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Hoover2022", 
         # add in the variable analyzed
         Variable = "GCC", 
         date = as.Date(date, format = "%m/%d/%Y"), 
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA)
  
str(hoover2022)

# check na's
hoover2022%>%
  filter(is.na(GCC)) # none

# check avs
hoover.avs<-hoover2022%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=n(),
    GCC.av=mean(GCC),
    GCC.sd=sd(GCC))

# view(hoover.avs) # all looks fine, leave alone
```
## Post2020
```{r}
str(Post2020_GCC)

post2020 <- Post2020_GCC %>%
  rename(plot = "Plot", 
         trt = "Trt", 
         date = "Date") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Post2020", 
         # add in the variable analyzed
         Variable = "GCC", 
         date = dmy(paste0(date, "-2017")), 
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA)
str(post2020)

# check na's
post2020%>%
  filter(is.na(GCC)) # none

# check avs
post20.avs<-post2020%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=n(),
    GCC.av=mean(GCC),
    GCC.sd=sd(GCC))

# view(post20.avs) # all looks fine, leave alone
```
## Post 2021
 
```{r}
str(Post2021_GCC)

post2021 <- Post2021_GCC %>%
  rename(plot = "Plot", 
         trt = "Trt", 
         date = "Date") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Post2021", 
         # add in the variable analyzed
         Variable = "GCC", 
         date = mdy(paste0(date, "_2018")), 
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA) %>%
  select(-Precip)
str(post2021)

# check na's
post2021%>%
  filter(is.na(GCC)) # none

# check avs
post21.avs<-post2021%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=n(),
    GCC.av=mean(GCC),
    GCC.sd=sd(GCC))

# view(post21.avs) # all looks fine, leave alone

```
## CCE

```{r}
str(CCE_GCC_updated)

cce <- CCE_GCC_updated %>%
  rename(
         trt = "treatment", 
         date = "Date", 
         GCC = "GCC_mean") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "CCE", 
         # add in the variable analyzed
         Variable = "GCC", 
         date = as.Date(date, format = "%m/%d/%y"), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_")) %>%
  select(-c(X.1, X, file_name, month, day, plot_type, nphoto, EGI_mean, ERI_mean, ExGmR, pixel_length, pixel_width, DoY))

str(cce)

# check na's
cce%>%
  filter(is.na(GCC)) # none

# check avs
cce.avs<-cce%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=n(),
    GCC.av=mean(GCC),
    GCC.sd=sd(GCC))

# view(cce.avs) # drop 8/20/2025 -- only one plot measured that day (missing other trt totally)

str(cce) # 1091
cce<-cce%>%
  filter(!date=="2025-08-20")
str(cce) # 1090
```

## Condon

```{r}
str(Condon_SLs_GCC)

condon_sl <- Condon_SLs_GCC %>%
  rename(plot = "Plot", 
         trt = "NewTrt", 
         date = "Date") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Condon_SL", 
         # add in the variable analyzed
         Variable = "GCC", 
         date = as.Date(date, format = "%m/%d/%y"), 
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA) %>%
  select(-c(Drop))

str(condon_sl)

# check na's
condon_sl%>%
  filter(is.na(GCC)) # lots of rows w/ plots missing

# check avs
con.avs<-condon_sl%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=sum(!is.na(GCC)),
    GCC.av=mean(GCC,na.rm=TRUE),
    GCC.sd=sd(GCC,na.rm=TRUE))

# view(con.avs) # OK -- all have at least 7-8 plots per trt per day still, leave alone
```

## Linabury

```{r}
str(Linabury_ChANGE_GCC)

linabury <- Linabury_ChANGE_GCC %>%
  rename( 
         trt = "treatment", 
         GCC = "gcc_mean") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Linabury_ChANGE", 
         # add in the variable analyzed
         Variable = "GCC", 
         date = as.Date(date, format = "%m/%d/%Y"), 
         study_trt = paste(Study_shorthand, trt, sep="_")) %>%
  select(-c(X, site, deluge.date.1, deluge.date.2, dom, month, experiment, nitrogen, deluge.date.1.doy, deluge.date.2.doy))

str(linabury)

# check na's
linabury%>%
  filter(is.na(GCC)) # none

# check avs
lin.avs<-linabury%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=n(),
    GCC.av=mean(GCC),
    GCC.sd=sd(GCC))

# view(lin.avs) # several days w/ only n=1 or 2 per trt -- this file doesn't have days since deluge so can't check it....leave data alone for now -- Mary checking

```

## combine

```{r}
combo <- rbind(hajek2024, hoover2022, post2020, post2021, cce, condon_sl, linabury)
str(combo)

#### quick vis together ####
ggplot(combo, aes(doy, GCC))+
  geom_point()+
  theme_bw()+
  facet_wrap(~Study_shorthand, scales="free") # no crazy obvious points -- export! 

# Export locally
write.csv(x = combo, row.names = F, na = '',
          file = file.path("deluge", "data", "R_exports", "GCC_harmomnized.csv"))

# Upload to Drive
googledrive::drive_upload(media = file.path("deluge", "data", "R_exports", "GCC_harmomnized.csv"), overwrite = T,
                          path = googledrive::as_id("https://drive.google.com/drive/folders/1dmzGwkGC1Y4uWW8nLXDkhtB_4A4suyF3"))
```


