---
title: "Soil Respiration"
author: "OLH"
date: "2026-03"
output: 
  bookdown::html_document2:
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: TRUE
    collapsed: TRUE
    theme: spacelab
    fig_caption: TRUE
    number_sections: FALSE
---
# Setup
<style>h1 {font-size: 24pt; } h2 {font-size: 20pt; } h3 {font-size: 18pt; } h4 {font-size: 16pt; } h5 {font-size: 14pt; } h6 {font-size: 12pt; } </style> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, dpi = 600, progress = FALSE, cache = FALSE, fig.width=5,  fig.height=3.5, fig.align="center")

options(repos = c(CRAN = "http://cran.rstudio.com"))
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, googledrive, supportR, lubridate)

`%!in%` = Negate(`%in%`)

```

# Create Folders on Desktop
```{r}
dir.create(file.path("deluge"), showWarnings = F)
dir.create(file.path("deluge", 'data'), showWarnings = F)
dir.create(file.path("deluge", 'data', 'R_exports'), showWarnings = F)
```

# Download resp files
```{r}
# Identify wanted files
files_drive <- googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1-z0EMfF8_LTWr3HZVajzcO3K9jKgYM9p")) %>% 
  dplyr::filter(stringr::str_detect(string = .$name, pattern = "Respiration.*\\.csv|\\.csv.*Respiration"))

# Did that work?
files_drive

# Identify local files
files_local <- dir(path = file.path("deluge", "data"))
files_local

# Overwrite local data files?
update <- TRUE

# Identify desired files
if(update == T) {
  files_wanted <- files_drive 
} else {
  files_wanted <- files_drive %>%
    dplyr::filter(!name %in% files_local)
}

# Download them!
purrr::walk2(.x = files_wanted$id, .y = files_wanted$name,
             .f = ~ googledrive::drive_download(file = .x, overwrite = T,
                                                path = file.path("deluge", "data", .y)))


```

# Read in all of the data
```{r}

# Get list of files with VWC in the filename
sr_files <- list.files(path = file.path("deluge", "data"), 
                        pattern = "Respiration", 
                        full.names = TRUE)

# Read each file and assign to a dataframe named after the file
for(f in sr_files) {
  # Extract just the filename without extension as the object name
  obj_name <- tools::file_path_sans_ext(basename(f))
  
  # Read the CSV and assign to an object with that name
  assign(obj_name, read.csv(f))
}

```

# Process Individual Files

## Hajek 2024

```{r}
str(Hajek2024_Soil_Respiration)
hajek2024 <- Hajek2024_Soil_Respiration %>%
  rename(plot = "Plot", 
         trt = "Trt", 
         date = "Date", 
         efflux = "Efflux") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Hajek2024", 
         # add in the variable analyzed
         Variable = "SR", 
         date = as.Date(date, format = "%d-%b-%y"), 
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA)%>%
  mutate(efflux=as.numeric(efflux))
  
str(hajek2024)

# double-check rows where as.numeric conversion failed
Hajek2024_Soil_Respiration %>%
  mutate(var = suppressWarnings(as.numeric(Efflux))) %>%
  filter(is.na(var) & !is.na(Efflux))  # all OK n/a --> NA

# check na's
hajek2024%>%
  filter(is.na(efflux)) # several dates, check avs

# check avs
hajek.avs<-hajek2024%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=sum(!is.na(efflux)),
    SR.av=mean(efflux,na.rm=TRUE),
    SR.sd=sd(efflux,na.rm=TRUE)) 

# view(hajek.avs) # drop 9/17/21 -- only one plot per trt, drop 3/23/22, only 2 per trt and looks like extra week b/t regular measures, keep 12/10/21 -- only 2 for Oct but 3 and 4 for other trts

str(hajek2024) # 488
hajek2024<-hajek2024%>%
  filter(!date %in% c("2021-09-17","2022-03-23"))
str(hajek2024) # 465 -- 23 measurements dropped
```

## Post 2020

```{r}
str(Post2020_Soil_Respiration)

post2020 <- Post2020_Soil_Respiration %>%
  rename(plot = "Plot", 
         trt = "Trt", 
         date = "Date",
         efflux = "Avg_Efflux") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Post2020", 
         # add in the variable analyzed
         Variable = "SR", 
         date = as.Date(date, format = "%m/%d/%Y"), 
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA) %>%
  select(-c(Time, Soil_Temp, VWC))
str(post2020)

# check na's
post2020%>%
  filter(is.na(efflux)) # none

# check avs
post20.avs<-post2020%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=n(),
    SR.av=mean(efflux),
    SR.sd=sd(efflux)) 
# view(post20.avs) # all OK, leave alone
```


## Post 2021

```{r}
str(Post2021_Soil_Respiration)

post2021 <- Post2021_Soil_Respiration %>%
  rename(plot = "Plot", 
         trt = "Trt", 
         date = "Date", 
         efflux = "Efflux") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Post2021", 
         # add in the variable analyzed
         Variable = "SR", 
         date = as.Date(date, format = "%m/%d/%Y"),  
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA) %>%
  select(-c(Soil_temp, VWC, Precip))
str(post2021)

# check na's
post2021%>%
  filter(is.na(efflux)) # none

# check avs
post21.avs<-post2021%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=n(),
    SR.av=mean(efflux),
    SR.sd=sd(efflux)) 
# view(post21.avs) # all OK, leave alone

```
## Hoover et al. 2022
```{r}
str(Hoover2022_soil_Respiration)

Hoover2022 <- Hoover2022_soil_Respiration %>%
  rename(plot = "Plot", 
         trt = "TRT", 
         date = "Date", 
         efflux = "Efflux") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Hoover2022", 
         # add in the variable analyzed
         Variable = "SR", 
         date = as.Date(date, format = "%Y-%m-%d"),  
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA) %>%
  select(-c(Observer, Soil_Temp, Time, CO2.Target, Soil_Temp, Soil.Moisture....,Efflux..umol.CO2.m.2.s., Soil.Temp..dgC.))

str(Hoover2022)

# check na's
Hoover2022%>%
  filter(is.na(efflux)) # three NA's on 8/23/2019

# check avs
hoover.avs<-Hoover2022%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=sum(!is.na(efflux)),
    SR.av=mean(efflux,na.rm=TRUE),
    SR.sd=sd(efflux,na.rm=TRUE)) 
# view(hoover.avs) # OK, NA plots from above just reduce n of day from 5-->4
```

## Condon
```{r}
str(Condon_SLs_Respiration)

Condon <- Condon_SLs_Respiration %>%
  rename(plot = "Plot", 
         trt = "NewTrt", 
         date = "Date", 
         efflux = "Efflux") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Condon_SL", 
         # add in the variable analyzed
         Variable = "SR", 
         date = as.Date(date, format = "%m/%d/%y"),  
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA) %>%
  select(-c(VWC, Soil_Temp, Drop_resp, Drop_temp))

str(Condon)

# check na's
Condon%>%
  filter(is.na(efflux)) # none

# check avs
con.avs<-Condon%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=n(),
    SR.av=mean(efflux),
    SR.sd=sd(efflux)) 
# view(con.avs) # all OK, amb always 10 per day and other trts 5/day

```
## Tooley

```{r}
str(Tooley_DRE_Respiration)

Tooley_DRE <- Tooley_DRE_Respiration %>%
  rename(treat=WaterTreatment,legacy=DroughtTreatment)%>%
  mutate(trt2=paste("Leg.",legacy,"_Trt.",treat,sep=""))%>%
  # update the treatment column 
    rename(plot = "Plot", 
         trt = "trt2", 
         date = "Date", 
         efflux = "Efflux") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "Tooley_DRE", 
         # add in the variable analyzed
         Variable = "SR", 
         date = as.Date(date, format = "%m/%d/%Y"),  
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA) %>%
  select(-c(treat, legacy)) %>%
  # fix 0025 date formatting 
  mutate(date=as.Date(date,format="%Y-%m-%d"),
         date=if_else(as.numeric(format(date,"%Y"))<100,
                      date+years(2000),
                      date))
str(Tooley_DRE)

# check na's
Tooley_DRE%>%
  filter(is.na(efflux)) # lots of NA rows, check w/ avs

# check avs
dre.avs<-Tooley_DRE%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=sum(!is.na(efflux)),
    SR.av=mean(efflux,na.rm=TRUE),
    SR.sd=sd(efflux,na.rm=TRUE)) 
# view(dre.avs) # drop 10/14/24 (n=0 or 1 per trt) -- 1/17/2025 and 2/8/2025 also have only n=1 per trt for at least 1 trt but ONLY Jan/Feb. measurements, so keep

str(Tooley_DRE) # 877
Tooley_DRE<-Tooley_DRE%>%
  filter(!date=="2024-10-14")
str(Tooley_DRE) # 853 -- ok
```

## CCE
```{r}
str(CCE_Soil_Respiration)

CCE <- CCE_Soil_Respiration %>%
  # update the treatment column 
    rename(plot = "Plot", 
         trt = "Treatment", 
         date = "Date", 
         efflux = "Efflux", 
         block = "Block") %>%
  # add in the shorthand name
  mutate(Study_shorthand = "CCE", 
         # add in the variable analyzed
         Variable = "SR", 
         date = as.Date(date, format = "%m/%d/%y"),  
         year = year(date), 
         doy = yday(date), 
         study_trt = paste(Study_shorthand, trt, sep="_"), 
         block = NA) %>%
  select(-c(Time, Target_CO2, SoilTemp, Observer, Notes))

str(CCE)

# check na's
CCE%>%
  filter(is.na(efflux)) # lots of NA rows, check w/ avs

# check avs
cce.avs<-CCE%>%
  group_by(date,trt)%>%
  dplyr::summarise(
    n.plots.per.day=sum(!is.na(efflux)),
    SR.av=mean(efflux,na.rm=TRUE),
    SR.sd=sd(efflux,na.rm=TRUE)) 
# view(cce.avs) # all days at least n=5/trt so OK, leave alone

```
# Merge all of the dataframes

```{r}
combo <- rbind(hajek2024, Hoover2022, post2020, post2021, CCE, Condon, Tooley_DRE)
str(combo)

#### quiz viz of all ####
ggplot(combo, aes(doy, efflux))+
  geom_point()+
  theme_bw()+
  facet_wrap(~Study_shorthand, scales="free") # OK- nothing looks too unreasonable

# Export locally
write.csv(x = combo, row.names = F, na = '',
          file = file.path("deluge", "data", "R_exports", "SR_harmonized.csv"))

# Upload to Drive
googledrive::drive_upload(media = file.path("deluge", "data", "R_exports", "SR_harmonized.csv"), overwrite = T,
                          path = googledrive::as_id("https://drive.google.com/drive/folders/1dmzGwkGC1Y4uWW8nLXDkhtB_4A4suyF3"))
```

