---
title: "Treatment_Standardizing_Filtering"
author: "Kathy Condon"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(tidyverse)
library(dplyr)
library(car)
library(emmeans)
library(multcomp)
library(lmerTest)
library(lme4)
library(RColorBrewer)
library(rstatix)
library(tidyr)
library(ggpubr)
library(lubridate)
library(ggtext)
library(ggh4x)
library(ggpattern)
library(data.table)
library(MuMIn)
library(scales)
library(performance)
library(googledrive)
```

```{r set file directories - local}
dir.create(file.path("deluge"), showWarnings = F)
dir.create(file.path("deluge","data"), showWarnings = F)
dir.create(file.path("deluge","data","R_exports"))
dir.create(file.path("deluge","figures"))
```

### inspecting raw treatment labels
```{r read in all CCE files}
## Read in drive folder (same folder as before)
drive.files <- googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1dmzGwkGC1Y4uWW8nLXDkhtB_4A4suyF3?usp=drive_link"))

## Filter to only files starting with "CCE_"
cce.files <- drive.files %>%
  dplyr::filter(stringr::str_starts(name, "CCE_"))

## Download each CCE file
for (i in seq_len(nrow(cce.files))) {
  file.name <- cce.files$name[i]
  file.id   <- cce.files$id[i]
  
  googledrive::drive_download(file = file.id,
                              overwrite = T,
                              path = file.path("deluge", "data", file.name))
  message("Downloaded: ", file.name)
}

# inspect CCE files
## List all downloaded CCE files locally
cce.local <- list.files(file.path("deluge", "data"), pattern = "^CCE_", full.names = TRUE)

## Read each into a named list
cce.list <- lapply(cce.local, read.csv)
names(cce.list) <- basename(cce.local)

## Inspect structure of each
lapply(cce.list, str)

## Check unique treatment names in each file — adjust "treatment" to your actual column name
lapply(cce.list, function(df) unique(df$treatment))

```



### for merged files

```{r read in selected treatments file}
# # read in the selected treatments file
# trts <- googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1fpoG0wLLqjFLkucR2ZlNMon31DIW1GH-")) %>%
#   dplyr::filter(name == "selected_treatments")
# 
# # Did that work?
# trts
# 
# # Download the excluded treatment file
# googledrive::drive_download(file = trts$id, overwrite = T, type = "csv",
#                             path = file.path("deluge", trts$name))
# 
# # Read in excluded treatment file
# excl_trt <- read.csv(file = file.path("deluge", "selected_treatments.csv"))
# str(excl_trt)

```

```{r Copy in productivity}
## list all productivity files in drive by name
harm.files<-c("ANPP_harmonized.csv","GCC_harmonized.csv","PRS_Nutrients_harmonized.csv","SR_harmonized.csv","VWC_20cm_harmonized.csv")

## read in drive folder
drive.files<-googledrive::drive_ls(googledrive::as_id("https://drive.google.com/drive/folders/1dmzGwkGC1Y4uWW8nLXDkhtB_4A4suyF3?usp=drive_link"))
  
## read in each file
for (i in harm.files){
  
file.name<-drive.files %>% 
  dplyr::filter(name == i) 

# if-else, to throw error if file name is incorrect or error would otherwise stop loop
if(nrow(file.name) == 1){
  googledrive::drive_download(file = file.name$id, 
                              overwrite = T,
                              path = file.path("deluge", 'data', i))
  
} else{
  message("File error - check name or if duplicated: ", i)
  }
}

```

```{r check all files}
ANPP<-read.csv("deluge/data/ANPP_harmonized.csv")
GCC<-read.csv("deluge/data/GCC_harmonized.csv")
PRS<-read.csv("deluge/data/PRS_Nutrients_harmonized.csv")
SR<-read.csv("deluge/data/SR_harmonized.csv")
VWC<-read.csv("deluge/data/VWC_20cm_harmonized.csv")

str(ANPP)
str(GCC)
str(PRS)
str(SR)
str(VWC)
```

```{r correct trt names}
#### ANPP ####
# check study shorthand and levels of trts in each
tapply(ANPP$trt,ANPP$Study_shorthand,unique)

# recode trts by study, leave trts we don't want out (replaced with NA) & filter out trt==NA
ANPP_recode <- ANPP %>%
  mutate(trt=as.character(trt))%>%
  mutate(trt=case_when(
    Study_shorthand == "CCE" ~ recode_values(trt, "1"~"CON", "2"~"DR", "3"~"CON_DEL", "4"~"DR_DEL"),
    Study_shorthand == "Condon_SL" ~ recode_values(trt, "amb"~"CON", "amb w/ deluge"~"CON_DEL"),
    Study_shorthand == "Hajek2024" ~ recode_values(trt, "OCT"~"OCT_DEL", "SEP"~"SEP_DEL", "AMB"~"CON"),
    Study_shorthand == "Hoover2022_CPER_DEX" ~ recode_values(trt, "DRT+DEL"~"DR_DEL", "DRT"~"DR"),
    Study_shorthand == "Linabury_ChANGE" ~ recode_values(trt, "control"~"CON", "deluge"~"CON_DEL"),
    Study_shorthand == "Post2020" ~ recode_values(trt, "A"~"EARLY_DEL", "B"~"MID_DEL", 
                                                  "C"~"LATE_DEL", "D"~"CON"),
    Study_shorthand == "Post2021" ~ recode_values(trt, "A"~"CON", "B"~"DEL_20", "C"~"DEL_40",
                                               "D"~"DEL_60", "E"~"DEL_80", "F"~"DEL_100", "G"~"DEL_120"),
    Study_shorthand == "Tooley_DRE" ~ recode_values(trt, "Leg.Drought_Trt.LTA"~"DR",
                                                 "Leg.Drought_Trt.Deluge"~"DR_DEL",
                                                 "Leg.Control_Trt.LTA"~"CON",
                                                 "Leg.Control_Trt.Deluge"~"CON_DEL")))%>%
  mutate(plot=if_else(
    Study_shorthand == "Linabury_ChANGE", 
    paste(as.factor(plot),as.factor(trt),sep="_"),
    as.factor(plot)))%>%
  filter(!is.na(trt))
  
# check data again and unique trts for each study
str(ANPP_recode)
tapply(ANPP_recode$trt,ANPP_recode$Study_shorthand,unique)

#### PRS ####
# check study shorthand and levels of trts in each
tapply(PRS$trt,PRS$Study_shorthand,unique)

# recode trts by study, leave trts we don't want out (replaced with NA) & filter out trt==NA
PRS_recode <- PRS %>%
  mutate(trt=as.character(trt))%>%
  mutate(trt=case_when(
    Study_shorthand == "CCE" ~ recode_values(trt, "Control"~"CON", "Drought"~"DR", 
                                             "Deluge"~"CON_DEL", "Drought-Deluge"~"DR_DEL"),
    Study_shorthand == "Condon_SLs" ~ recode_values(trt, "amb"~"CON", "amb w/ deluge"~"CON_DEL"),
    Study_shorthand == "Hajek2024" ~ recode_values(trt, "OCT"~"OCT_DEL", "SEP"~"SEP_DEL", "AMB"~"CON"),
    Study_shorthand == "Linabury_ChANGE" ~ recode_values(trt, "control"~"CON", "deluge"~"CON_DEL"),
    Study_shorthand == "Tooley_DRE" ~ recode_values(trt, "Leg.Drought_Trt.LTA"~"DR",
                                                 "Leg.Drought_Trt.Deluge"~"DR_DEL",
                                                 "Leg.Control_Trt.LTA"~"CON",
                                                 "Leg.Control_Trt.Deluge"~"CON_DEL")))%>%
  mutate(plot=if_else(
    Study_shorthand == "Linabury_ChANGE", 
    paste(as.factor(plot),as.factor(trt),sep="_"),
    as.factor(plot)))%>%
  # fit mismatched name of my study
  mutate(Study_shorthand=if_else(Study_shorthand=="Condon_SLs","Condon_SL",Study_shorthand))%>%
  filter(!is.na(trt))
  
# check data again and unique trts for each study
str(PRS_recode)
tapply(PRS_recode$trt,PRS_recode$Study_shorthand,unique)

#### GCC ####
# check study shorthand and levels of trts in each
tapply(GCC$trt,GCC$Study_shorthand,unique)

# add in Greg GCC data (sent later than everyone else - skipping initial filtering and harmonizing to add just here now)
Tooley_path<-googledrive::drive_download(file = "Tooley_DRE_GCC.csv", 
                              overwrite = T,
                              path = file.path("deluge", 'data',"Tooley_DRE_GCC.csv"))
Tooley_GCC<-read.csv("deluge/data/Tooley_DRE_GCC.csv")

Tooley_DRE_recode<-Tooley_GCC%>%
  mutate(trt=paste("Leg.",DroughtTreatment,"_","Trt.",WaterTreatment,sep=""),
         Study_shorthand="Tooley_DRE",
         study_trt=paste(Study_shorthand,trt,sep="_"),
         Variable="GCC",
         block=NA)%>%
  filter(WaterTreatment %in% c("LTA","Deluge"))%>%
  rename(date=Date,plot=Plot,year=Year,GCC=Greenness)%>%
  mutate(date=as.Date(date,format="%Y-%m-%d"),
         doy=yday(date))%>%
  select(c(date,plot,trt,GCC,Study_shorthand,Variable,year,doy,study_trt,block))

str(Tooley_DRE_recode)

# combine Tooley in
GCC_add<-rbind(GCC,Tooley_DRE_recode)
GCC<-GCC_add # replace GCC
str(GCC)

# recode trts by study, leave trts we don't want out (replaced with NA) & filter out trt==NA
GCC_recode <- GCC %>%
  mutate(trt=as.character(trt))%>%
  mutate(trt=case_when(
    Study_shorthand == "CCE" ~ recode_values(trt, "Control"~"CON", "Drought"~"DR", 
                                             "Deluge"~"CON_DEL", "Drought-Deluge"~"DR_DEL"),
    Study_shorthand == "Condon_SL" ~ recode_values(trt, "amb"~"CON", "amb w/ deluge"~"CON_DEL"),
    Study_shorthand == "Hajek2024" ~ recode_values(trt, "OCT"~"OCT_DEL", "SEP"~"SEP_DEL", "AMB"~"CON"),
    Study_shorthand == "Hoover2022" ~ recode_values(trt, "DRT+DEL"~"DR_DEL", "DRT"~"DR"),
    Study_shorthand == "Linabury_ChANGE" ~ recode_values(trt, "control"~"CON", "deluge"~"CON_DEL"),
    Study_shorthand == "Post2020" ~ recode_values(trt, "A"~"EARLY_DEL", "B"~"MID_DEL", 
                                                  "C"~"LATE_DEL", "D"~"CON"),
    Study_shorthand == "Post2021" ~ recode_values(trt, "A"~"CON", "B"~"DEL_20", "C"~"DEL_40",
                                               "D"~"DEL_60", "E"~"DEL_80", "F"~"DEL_100", "G"~"DEL_120"),
    Study_shorthand == "Tooley_DRE" ~ recode_values(trt, "Leg.Drought_Trt.LTA"~"DR",
                                                 "Leg.Drought_Trt.Deluge"~"DR_DEL",
                                                 "Leg.Control_Trt.LTA"~"CON",
                                                 "Leg.Control_Trt.Deluge"~"CON_DEL")))%>%
  mutate(plot=if_else(
    Study_shorthand == "Linabury_ChANGE", 
    paste(as.factor(plot),as.factor(trt),sep="_"),
    as.factor(plot)))%>%
  filter(!is.na(trt))
  
# check data again and unique trts for each study
str(GCC_recode)
tapply(GCC_recode$trt,GCC_recode$Study_shorthand,unique)

#### SR ####
# check study shorthand and levels of trts in each
tapply(SR$trt,SR$Study_shorthand,unique)

# recode trts by study, leave trts we don't want out (replaced with NA) & filter out trt==NA
SR_recode <- SR %>%
  mutate(trt=as.character(trt))%>%
  mutate(trt=case_when(
    Study_shorthand == "CCE" ~ recode_values(trt, "Control"~"CON", "Drought"~"DR", 
                                             "Deluge"~"CON_DEL", "Drought-Deluge"~"DR_DEL"),
    Study_shorthand == "Condon_SL" ~ recode_values(trt, "amb"~"CON", "amb w/ deluge"~"CON_DEL"),
    Study_shorthand == "Hajek2024" ~ recode_values(trt, "OCT"~"OCT_DEL", "SEP"~"SEP_DEL", "AMB"~"CON"),
    Study_shorthand == "Hoover2022" ~ recode_values(trt, "4"~"DR_DEL", "3"~"DR"),
    Study_shorthand == "Post2020" ~ recode_values(trt, "A"~"EARLY_DEL", "B"~"MID_DEL", 
                                                  "C"~"LATE_DEL", "D"~"CON"),
    Study_shorthand == "Post2021" ~ recode_values(trt, "A"~"CON", "B"~"DEL_20", "C"~"DEL_40",
                                               "D"~"DEL_60", "E"~"DEL_80", "F"~"DEL_100", "G"~"DEL_120"),
    Study_shorthand == "Tooley_DRE" ~ recode_values(trt, "Leg.Drought_Trt.LTA"~"DR",
                                                 "Leg.Drought_Trt.Deluge"~"DR_DEL",
                                                 "Leg.Control_Trt.LTA"~"CON",
                                                 "Leg.Control_Trt.Deluge"~"CON_DEL")))%>%
  filter(!is.na(trt))
  
# check data again and unique trts for each study
str(SR_recode)
tapply(SR_recode$trt,SR_recode$Study_shorthand,unique)


#### VWC ####
# check study shorthand and levels of trts in each
tapply(VWC$trt,VWC$Study_shorthand,unique)

# recode trts by study, leave trts we don't want out (replaced with NA) & filter out trt==NA
VWC_recode <- VWC %>%
  mutate(trt=as.character(trt))%>%
  mutate(trt=case_when(
    Study_shorthand == "CCE" ~ recode_values(trt, "Control"~"CON", "Drought"~"DR", 
                                             "Deluge"~"CON_DEL", "Drought-Deluge"~"DR_DEL"),
    Study_shorthand == "Condon_SL" ~ recode_values(trt, "amb"~"CON", "amb w/ deluge"~"CON_DEL"),
    Study_shorthand == "Hajek2024" ~ recode_values(trt, "OCT"~"OCT_DEL", "SEP"~"SEP_DEL", "AMB"~"CON"),
    Study_shorthand == "Hoover2022" ~ recode_values(trt, "DRT+DEL"~"DR_DEL", "DRT"~"DR"),
    Study_shorthand == "Linabury_ChANGE" ~ recode_values(trt, "control"~"CON", "deluge"~"CON_DEL"),
    Study_shorthand == "Post2020" ~ recode_values(trt, "A"~"EARLY_DEL", "B"~"MID_DEL", 
                                                  "C"~"LATE_DEL", "D"~"CON"),
    Study_shorthand == "Post2021" ~ recode_values(trt, "A"~"CON", "B"~"DEL_20", "C"~"DEL_40",
                                               "D"~"DEL_60", "E"~"DEL_80", "F"~"DEL_100", "G"~"DEL_120"),
    Study_shorthand == "Tooley_DRE" ~ recode_values(trt, "Leg.Drought_Trt.LTA"~"DR",
                                                 "Leg.Drought_Trt.Deluge"~"DR_DEL",
                                                 "Leg.Control_Trt.LTA"~"CON",
                                                 "Leg.Control_Trt.Deluge"~"CON_DEL")))%>%
  mutate(plot=if_else(
    Study_shorthand == "Linabury_ChANGE", 
    paste(as.factor(plot),as.factor(trt),sep="_"),
    as.factor(plot)))%>%
  filter(!is.na(trt))

# check data again and unique trts for each study
str(VWC_recode)
tapply(VWC_recode$trt,VWC_recode$Study_shorthand,unique)

```

```{r export filtered datafiles}
# sanity check each
str(ANPP) # 1957
str(ANPP_recode) # 1437

str(PRS) # 2122
str(PRS_recode) # 2064

str(GCC) # 4937
str(GCC_recode) # 4017

str(SR) # 4285
str(SR_recode) # 3613

str(VWC) # 7627
str(VWC_recode) # 6003
# view(VWC_recode)

# export each
# ANPP
write.csv(ANPP_recode, "ANPP_filtered.csv", row.names = FALSE)

drive_upload(
  media = "ANPP_filtered.csv",
  path = file.path("deluge", "data","R_exports"),
  name = "ANPP_filtered.csv",
  overwrite = T)

# PRS
write.csv(PRS_recode, "PRS_filtered.csv", row.names = FALSE)

drive_upload(
  media = "PRS_filtered.csv",
  path = file.path("deluge", "data","R_exports"),
  name = "PRS_filtered.csv",
  overwrite = T)

# GCC
write.csv(GCC_recode, "GCC_filtered.csv", row.names = FALSE)

drive_upload(
  media = "GCC_filtered.csv",
  path = file.path("deluge", "data","R_exports"),
  name = "GCC_filtered.csv",
  overwrite = T)

# SR
write.csv(SR_recode, "SR_filtered.csv", row.names = FALSE)

drive_upload(
  media = "SR_filtered.csv",
  path = file.path("deluge", "data","R_exports"),
  name = "SR_filtered.csv",
  overwrite = T)

# VWC
write.csv(VWC_recode, "VWC_20cm_filtered.csv", row.names = FALSE)

drive_upload(
  media = "VWC_20cm_filtered.csv",
  path = file.path("deluge", "data","R_exports"),
  name = "VWC_20cm_filtered.csv")

```

